/*************************************************
 * I18N (다국어 확장 버전)
 *************************************************/
const i18n = {
  EN: {
    appTitle: "HTORI ERP",
    sidebar: {
      dashboard: "Dashboard",
      stock: "Stock",
      purchase: "Purchase",
      outgoing: "Outgoing",
      production: "Production",
      bom: "BOM",
      outsourcing: "Outsourcing",
      finished: "Finished Goods",
      employees: "Employees",
      attendance: "Attendance",
      payroll: "Payroll",
      logs: "Logs",
      suppliers: "Suppliers",
      settings: "Settings",
    },
    pages: {
      dashboardTitle: "Dashboard",
      dashboardDesc: "Factory indicators and charts.",
      stockTitle: "Stock",
      stockDesc: "Raw / semi-finished / finished inventory.",
      purchaseTitle: "Purchase",
      purchaseDesc: "Incoming materials.",
      purchaseFormCodePlaceholder: "Material Code",
      purchaseFormNamePlaceholder: "Material Name",
      purchaseFormQtyPlaceholder: "Qty",
      outgoingTitle: "Outgoing",
      outgoingDesc: "Manual outgoing.",
      productionTitle: "Production",
      productionDesc: "Production and material usage.",
      bomTitle: "BOM",
      bomDesc: "Bill of Materials.",
      outsourcingTitle: "Outsourcing",
      outsourcingDesc: "Out → In with vendor and defect.",
      finishedTitle: "Finished Goods",
      finishedDesc: "Finished products stock.",
      suppliersTitle: "Supplier Management",
      suppliersDesc: "Add / delete suppliers.",
      suppliersChartTitle: "Supplier Monthly Chart (last 6 months)",
      logsTitle: "Logs",
      logsDesc: "System activity history.",
      settingsTitle: "Settings",
      settingsDesc: "ERP basic settings.",
      dashRawLabel: "Raw Material Stock",
      dashFinishedLabel: "Finished Goods Stock",
      dashTodayProdLabel: "Today Production",
      dashDefectLabel: "Outsourcing Defect Rate",
      dashPurchase7Title: "Purchase (7 days)",
      dashOutgoing7Title: "Outgoing (7 days)",
      dashProduction7Title: "Production (7 days)",
      employeesTitle: "Employees",
      employeesDesc: "Employee master data.",
      attendanceTitle: "Attendance",
      attendanceDesc: "Clock-in / Clock-out records.",
      payrollTitle: "Payroll",
      payrollDesc: "Monthly payroll overview.",
    },
    common: {
      add: "Add",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      close: "Close",
      register: "Register",
      pdfExport: "PDF Export",
      excelDownload: "Excel Download",
      productCode: "Product Code",         // Production placeholder
      backup: "Backup",
      restore: "Restore",

      // Supplier fields
      supplierName: "Supplier Name",
      vendorName: "Vendor Name",
      contactPerson: "Contact Person",
      email: "Email",
      address: "Address",
      phone: "Phone",
      bankName: "Bank Name",
      bankAccount: "Account Number",
      bankHolder: "Account Holder",

      // Supplier modal / AP
      supplierModalTitle: "Supplier Detail",
      apTitle: "AP Payment (Outstanding)",
      apAmountPlaceholder: "Amount to Pay",
      apRegister: "Register Payment",

      // BOM / Outsourcing
      bomSave: "Save BOM",
      outsourcingRegister: "Register Outsourcing",
    },
  },

  KR: {
    appTitle: "HTORI ERP",
    sidebar: {
      dashboard: "대시보드",
      stock: "재고",
      purchase: "입고",
      outgoing: "출고",
      production: "생산",
      bom: "BOM",
      outsourcing: "외주",
      finished: "완제품",
      employees: "직원",
      attendance: "근태",
      payroll: "급여",
      logs: "로그",
      suppliers: "공급업체",
      settings: "설정",
    },
    pages: {
      dashboardTitle: "대시보드",
      dashboardDesc: "공장 지표 및 그래프.",
      stockTitle: "재고 관리",
      stockDesc: "원자재 / 반제품 / 완제품 재고.",
      purchaseTitle: "입고 관리",
      purchaseDesc: "자재 입고 기록.",
      purchaseFormCodePlaceholder: "자재 코드",
      purchaseFormNamePlaceholder: "자재 이름",
      purchaseFormQtyPlaceholder: "수량",
      outgoingTitle: "출고 관리",
      outgoingDesc: "자재 출고 기록.",
      productionTitle: "생산 관리",
      productionDesc: "생산 및 자재 사용.",
      bomTitle: "BOM 관리",
      bomDesc: "제품별 필요 자재.",
      outsourcingTitle: "외주 관리",
      outsourcingDesc: "외주 출고/입고 및 불량.",
      finishedTitle: "완제품 재고",
      finishedDesc: "완제품 재고 현황.",
      suppliersTitle: "공급업체 관리",
      suppliersDesc: "공급업체 추가/삭제.",
      suppliersChartTitle: "공급업체 월별 그래프 (최근 6개월)",
      logsTitle: "로그",
      logsDesc: "시스템 작업 기록.",
      settingsTitle: "설정",
      settingsDesc: "기본 설정.",
      dashRawLabel: "원자재 재고",
      dashFinishedLabel: "완제품 재고",
      dashTodayProdLabel: "오늘 생산량",
      dashDefectLabel: "외주 불량률",
      dashPurchase7Title: "입고 (7일)",
      dashOutgoing7Title: "출고 (7일)",
      dashProduction7Title: "생산 (7일)",
      employeesTitle: "직원 관리",
      employeesDesc: "직원 기본 정보.",
      attendanceTitle: "근태 관리",
      attendanceDesc: "출근/퇴근 기록.",
      payrollTitle: "급여 관리",
      payrollDesc: "월별 급여 현황.",
    },
    common: {
      add: "추가",
      edit: "수정",
      delete: "삭제",
      save: "저장",
      close: "닫기",
      register: "등록",
      pdfExport: "PDF 다운로드",
      excelDownload: "Excel 다운로드",
      productCode: "완제품 코드",
      backup: "백업",
      restore: "복원",

      // Supplier fields
      supplierName: "공급업체명",
      vendorName: "벤더명",
      contactPerson: "담당자",
      email: "이메일",
      address: "주소",
      phone: "전화번호",
      bankName: "은행명",
      bankAccount: "계좌번호",
      bankHolder: "예금주",

      // Supplier modal / AP
      supplierModalTitle: "공급업체 상세",
      apTitle: "AP 결제 (미지급 정리)",
      apAmountPlaceholder: "결제 금액",
      apRegister: "결제 등록",

      // BOM / Outsourcing
      bomSave: "BOM 저장",
      outsourcingRegister: "외주 등록",
    },
  },

  ID: {
    appTitle: "HTORI ERP",
    sidebar: {
      dashboard: "Dashboard",
      stock: "Stok",
      purchase: "Pembelian",
      outgoing: "Pengeluaran",
      production: "Produksi",
      bom: "BOM",
      outsourcing: "Outsourcing",
      finished: "Barang Jadi",
      employees: "Karyawan",
      attendance: "Absensi",
      payroll: "Gaji",
      logs: "Log",
      suppliers: "Pemasok",
      settings: "Pengaturan",
    },
    pages: {
      dashboardTitle: "Dashboard",
      dashboardDesc: "Indikator dan grafik pabrik.",
      stockTitle: "Stok",
      stockDesc: "Stok bahan baku / semi / jadi.",
      purchaseTitle: "Pembelian",
      purchaseDesc: "Data bahan masuk.",
      purchaseFormCodePlaceholder: "Kode Material",
      purchaseFormNamePlaceholder: "Nama Material",
      purchaseFormQtyPlaceholder: "Qty",
      outgoingTitle: "Pengeluaran",
      outgoingDesc: "Data bahan keluar.",
      productionTitle: "Produksi",
      productionDesc: "Produksi & pemakaian bahan.",
      bomTitle: "BOM",
      bomDesc: "Bill of Materials.",
      outsourcingTitle: "Outsourcing",
      outsourcingDesc: "Out → In dengan vendor.",
      finishedTitle: "Barang Jadi",
      finishedDesc: "Stok barang jadi.",
      suppliersTitle: "Manajemen Supplier",
      suppliersDesc: "Tambah / hapus supplier.",
      suppliersChartTitle: "Grafik Bulanan Supplier (6 bulan terakhir)",
      logsTitle: "Log",
      logsDesc: "Riwayat aktivitas.",
      settingsTitle: "Pengaturan",
      settingsDesc: "Pengaturan dasar.",
      dashRawLabel: "Stok Bahan Baku",
      dashFinishedLabel: "Stok Barang Jadi",
      dashTodayProdLabel: "Produksi Hari Ini",
      dashDefectLabel: "Tingkat Cacat Outsourcing",
      dashPurchase7Title: "Pembelian (7 hari)",
      dashOutgoing7Title: "Pengeluaran (7 hari)",
      dashProduction7Title: "Produksi (7 hari)",
      employeesTitle: "Karyawan",
      employeesDesc: "Data karyawan.",
      attendanceTitle: "Absensi",
      attendanceDesc: "Data masuk / pulang.",
      payrollTitle: "Gaji",
      payrollDesc: "Ringkasan gaji bulanan.",
    },
    common: {
      add: "Tambah",
      edit: "Edit",
      delete: "Hapus",
      save: "Simpan",
      close: "Tutup",
      register: "Daftar",
      pdfExport: "Ekspor PDF",
      excelDownload: "Unduh Excel",
      productCode: "Kode Produk",
      backup: "Backup",
      restore: "Restore",

      // Supplier fields
      supplierName: "Nama Supplier",
      vendorName: "Nama Vendor",
      contactPerson: "Kontak",
      email: "Email",
      address: "Alamat",
      phone: "Telepon",
      bankName: "Nama Bank",
      bankAccount: "No. Rekening",
      bankHolder: "Nama Pemilik",

      // Supplier modal / AP
      supplierModalTitle: "Detail Supplier",
      apTitle: "Pembayaran AP (Hutang)",
      apAmountPlaceholder: "Jumlah Pembayaran",
      apRegister: "Catat Pembayaran",

      // BOM / Outsourcing
      bomSave: "Simpan BOM",
      outsourcingRegister: "Daftar Outsourcing",
    },
  },
};
